version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "5000:5000"
  app:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
