apiVersion: v1
kind: Service
metadata:
  name: zad3-service
  labels:
    app: zad3

spec:
  selector:
    app: zad1

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

  type: NodePort
