apiVersion: v1
kind: Pod
metadata:
  name: zad4-pod
  labels:
    app: zad4

spec:
  containers:
  - name: react-app
    image: tusiaa/react_app

---

apiVersion: v1
kind: Service
metadata:
  name: zad4-service
  labels:
    app: zad4

spec:
  selector:
    app: zad4-pod

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300

  type: NodePort
