services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "80:80"
  react_app:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    environment:
      - CHOKIDAR_USEPOLLING="true"
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    volumes:
      - /home/node/app/node_modules
      - ./app:/home/node/app
    
