apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  namespace: development
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend

  replicas: 2
  template: 
    metadata:
      labels: 
        app: backend
        
    spec:
      containers:
      - name: books-backend
        image: tusiaa/books-api:release-1.1
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MONGO_URL
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: REDIS_PORT

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: development
  labels:
    app: backend

spec:
  selector:
    app: backend

  ports:
    - port: 3001
      targetPort: 3001
      