apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: mongodb

  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_PASSWORD
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MONGO_DB

      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: development
  labels:
    app: mongodb

spec:
  selector:
    app: mongodb

  ports:
  - port: 27017
    targetPort: 27017

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
