apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  MONGO_URL: mongodb-service
  MONGO_DB: books
  REDIS_PORT: "6379"
  REDIS_HOST: redisdb-service
